version: '2'

services:
  app:
    build: smtp2mattermost
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/locale.conf:/etc/locale.conf:ro
    ports:
      - "8025:8025"
    environment:
      - MATTERMOST_INCOME_URL=http://xxx.xxx.xxx/hooks/xxxxxxxxxxxxxxxxxxxxx
      - MATTERMOST_ADDRESS=xxx.xxx.xxx.xxx
      - MATTERMOST_LOGIN_ID=xxx@xxx.xxx.xxx
      - MATTERMOST_PASSWORD=xxx
      - MATTERMOST_PORT=xxx
      - MATTERMOST_EXCLUDE_NOTIFICATE=xxx
