version: '2'

services:
  app:
    build: smtp2mattermost
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/locale.conf:/etc/locale.conf:ro
    ports:
      - "8025:1025"
    environment:
      - MATTERMOST_ADDRESS=xxx.xxx.xxx.xxx
      - MATTERMOST_LOGIN_ID=xxx
      - MATTERMOST_PASSWORD=xxx
      - MATTERMOST_PORT=xxx
